Add support for wrapped messages and custom popup sizes
ktsu-dev/ImGuiPopups pull request #37
Opened 2024-10-10 04:31 UTC by Damon3000s

- Sometimes you want to display a message to the user but don't require any additional feedback. That is what MessageOK is for. The problem is when you need to display a LOT of information to the user where the interface doesn't work.
- MessageOK only renders text unformatted which means any line of text which is too wide for the popup will be clipped making it unreadable.
- Added additional functionality to the Popup classes so we can specify that text should be displayed wrapped, and the size of the popup.

2024-10-10 05:55 UTC, matt-edmondson requested changes
Please add custom size support to the other uses of Modal to keep the feature set consistent across the popup types.

2024-10-10 05:55 UTC, matt-edmondson commented on ImGuiPopupsDemo/ImGuiPopupsDemo.cs
> +			popupMessageOK.Open("Wall Of Text", message, true, new Vector2(ImGui.GetContentRegionAvail().X * 0.75f, -1.0f));
I would prefer not to use a bool as a parameter here, consider an enum to improve readability.

2024-10-10 22:50 UTC, Damon3000s commented
Feedback addressed.

2024-10-14 04:35 UTC, matt-edmondson approved these changes
thanks damo

2024-10-14 04:36 UTC, merged